# Project information
site_name: "Fitness Management System"
docs_dir: docs  # Where to find the English markdown files
site_dir: site  # Where to put the English HTML files
site_author: 'Hikmethan Kolay'
site_url: 'https://github.com/hikmethankolay/ce100-final-hikmethan-kolay-yagizemre-ozbilge-csharp'
site_description: >-
    Fitness Management System

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/ucoruh/vs-net-core-template'
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2019 - 2023 Uğur CORUH

theme:
  name: material
  
nav:
    - Introduction: 'index.md'
    - Developers: 'developers.md'
    - 'Doxygen': 'doxygen/html/index.html'
    - 'Test Coverage': 'coveragereport/index.html'
    - 'Doc Coverage': 'coverxygen/index.html'